update: add database

diff --git a/conf/lamp b/conf/lamp
--- a/conf/lamp
+++ b/conf/lamp
@@ -12,7 +12,7 @@ apache_location=/usr/local/apache
 
 rootness(){
     if [[ $EUID -ne 0 ]]; then
-        echo "This script must be run as root" 1>&2
+        echo "Error: This script must be run as root" 1>&2
         exit 1
     fi
 }
@@ -34,11 +34,11 @@ set_apache_allow_syntax(){
         elif /usr/sbin/httpd -v | grep -q "Apache/2.2"; then
             allow_from_all="Allow from All"
         else
-            echo "Can not get Apache version..."
+            echo "Error: Can not get Apache version..."
             exit 1
         fi
     else
-        echo "Can not find Apache, may be not installed. Please check it and try again."
+        echo "Error: Can not find Apache, may be not installed. Please check it and try again."
         exit 1
     fi
 }
@@ -51,7 +51,7 @@ vhost_add(){
         read -p "Please enter server names(like this:www.lamp.sh lamp.sh): " server_names
         for i in ${server_names};do
             if apache_vhost_is_exist $i;then
-                echo "vhost $i is exist, please reinput server names."
+                echo "Error: vhost [$i] is exist, please check it and try again."
                 break
             fi
             break 2
@@ -64,6 +64,48 @@ vhost_add(){
     php_admin_value=""
     if [ -s /usr/bin/php ];then
         php_admin_value="php_admin_value open_basedir ${website_root}:/tmp:/proc"
+    fi
+
+    while :
+    do
+        read -p "Do you want to create database?[y/n]:" create
+        case ${create} in
+        y|Y)
+            if [ ! "$(command -v "mysql")" ]; then
+                echo "Error: MySQL or MariaDB is not installed, please check it and try again."
+                exit 1
+            fi
+            read -p "Please enter your MySQL or MariaDB root password:" mysqlroot_passwd
+            mysql -uroot -p${mysqlroot_passwd} <<EOF
+exit
+EOF
+            if [ $? -ne 0 ]; then
+                echo "Error: MySQL or MariaDB root password incorrect! Please check it and try again!"
+                exit 1
+            fi
+            read -p "Please enter the database name:" dbname
+            [ -z ${dbname} ] && echo "Error: database name can not be empty." && exit 1
+            read -p "Please set the password for user ${dbname}:" mysqlpwd
+            [ -z ${mysqlpwd} ] && echo "Error: user password can not be empty." && exit 1
+            create="y"
+            break
+            ;;
+        n|N)
+            echo "Don't create database."
+            create="n"
+            break
+            ;;
+        *) echo "Please enter only y or n"
+        esac
+    done
+
+    if [ "$create" == "y" ]; then
+        mysql -uroot -p${mysqlroot_passwd} <<EOF
+CREATE DATABASE IF NOT EXISTS \`${dbname}\`;
+GRANT ALL PRIVILEGES ON \`${dbname}\` . * TO '${dbname}'@'localhost' IDENTIFIED BY '${mysqlpwd}';
+GRANT ALL PRIVILEGES ON \`${dbname}\` . * TO '${dbname}'@'127.0.0.1' IDENTIFIED BY '${mysqlpwd}';
+FLUSH PRIVILEGES;
+EOF
     fi
 
     cat > ${apache_location}/conf/vhost/${server_names%% *}.conf << EOF
@@ -94,7 +136,7 @@ EOF
         /etc/init.d/httpd restart
         echo "Reload success."
     else
-        echo "Reload failed! config file had an error, please fix it and try again."
+        echo "Error: Reload failed! config file had an error, please fix it and try again."
         exit 1
     fi
 }
@@ -110,15 +152,15 @@ vhost_del(){
         exit 1
     else
         rm -f ${apache_location}/conf/vhost/${domain}.conf
-        echo "Complete deleted the server_name [${domain}] of vhost."
+        echo "Delete the server name [${domain}] of vhost completed."
 
         echo "Reloading the apache config file..."
         if ${apache_location}/bin/apachectl -t;then
             /etc/init.d/httpd restart
             echo "Reload success."
         else
-             echo "Reload failed! config file had an error, please fix it and try again."
-             exit 1
+            echo "Error: Reload failed! config file had an error, please fix it and try again."
+            exit 1
         fi
     fi
 }
